Dockerfile: Use the latest available python version.
Otherwise other packages we need might fail to install.  E.g., ovsdbapp
requires Python >= 3.10:

  ERROR: Package 'ovsdbapp' requires a different Python: 3.9.25 not in '>=3.10'
  Error: building at STEP "RUN pip3 install -r /ovn-tester/requirements.txt":
  while running runtime: exit status 1

For RHEL we query the available packages and choose the most recent
python3 version and the corresponding python3.x-pip package.  For Fedora
and Deb-based distros we use the python3 version pulled in by the
python3-pip package.

Suggested-by: Ilya Maximets <i.maximets@ovn.org>
Signed-off-by: Dumitru Ceara <dceara@redhat.com>